version: '3'

services:
  magento:
    build: ./magento
    ports:
      - 9090:80
      - 9092:443
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./src:/var/www/html
    networks:
      webnet:
        aliases:
          - magento2.com

  db:
    build: ./data
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - webnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 9091:80
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: magento
    networks:
      - webnet
networks:
  webnet:
